# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'tumtum' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking', '~> 2.6'

  # Pods for tumtum

  target 'tumtumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tumtumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
