# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Tumb' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  pod 'AFNetworking', '~> 2.6'
  use_frameworks!

  target 'TumbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TumbUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
