# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'tum' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  pod 'AFNetworking', '~> 2.6'
  use_frameworks!

  # Pods for tum

  target 'tumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
